'use strict';

// Alle Texte der Oberfläche in Deutsch und Englisch. Die Sprache folgt der
// Einstellung "sprachcode".

const TEXTE = {
  de: {
    'tray.tooltip': '{name}',
    'tray.chat': 'Chat öffnen',
    'tray.sprechen': 'Sprechen',
    'tray.overlay': 'Overlay ein/aus',
    'einst.tageslimit': 'Kostenbremse: Tageslimit in US-$ (0 = aus)',
    'einst.kosten_heute': 'Heute bisher: {usd} US-$ in {anfragen} Anfragen (geschätzt nach Listenpreis).',
    'hinweis.kosten_warnung': 'Heute sind schon 80 % des Kostenlimits verbraucht.',
    'protokoll.verletzt': 'Das Protokoll wurde nachträglich verändert (Zeile {zeile}). Bitte prüfen, wer an protokoll.jsonl war.',
    'tray.weckwort': 'Auf „Hey {name}" hören',
    'tray.tooltip_weckwort': '{name} – hört auf „Hey {name}"',
    'einst.weckwort': 'Auf „Hey {name}" hören',
    'einst.weckwort_hinweis': 'Das Mikrofon bleibt dafür offen. Erkannt wird nur das Aktivierungswort, direkt auf dem PC – nichts wird aufgenommen oder verschickt. Solange {name} selbst zuhört oder spricht, pausiert es.',
    'einst.weckwort_schwelle': 'Erkennungsschwelle',
    'weckwort.kein_mikrofon': '„Hey {name}" braucht ein Mikrofon. Bitte eines anschließen oder in den Windows-Soundeinstellungen als Standard-Aufnahmegerät wählen und das Aktivierungswort neu einschalten.',
    'weckwort.fehler': 'Für „Hey {name}" braucht Windows die Spracherkennung für {sprache}. Bitte unter Einstellungen → Zeit und Sprache → Sprache nachrüsten.',
    'erinnerung.titel': '⏰ Erinnerung',
    'erinnerung.verspaetet': 'Verpasst (war für {zeit}): {text}',
    'einst.erinnerung_vorlesen': 'Erinnerungen vorlesen',
    'chat.schliessen': 'Schließen',
    'einst.overlay': 'Overlay (Gaming)',
    'einst.overlay_hinweis': 'Ein kleines Chatfenster über Spielen im Fenster- oder randlosen Vollbild. Bei exklusivem Vollbild zeigt Windows keine Overlays. Hotkey leer lassen, um es abzuschalten.',
    'einst.hotkey_overlay': 'Hotkey Overlay',
    'einst.overlay_deckkraft': 'Deckkraft',
    'einst.overlay_bei_antwort': 'Bei Sprachbefehlen',
    'einst.overlay_aus': 'nichts einblenden',
    'einst.overlay_passiv': 'Antwort kurz einblenden (durchklickbar)',
    'tray.blase': 'Blase anzeigen',
    'tray.einstellungen': 'Einstellungen …',
    'tray.neu': 'Neues Gespräch',
    'tray.updates': 'Nach Updates suchen',
    'tray.protokoll': 'Protokoll öffnen',
    'tray.beenden': 'Beenden',

    'chat.titel': '{name}',
    'chat.platzhalter': 'Schreib {name} etwas …',
    'chat.senden': 'Senden',
    'chat.stopp': 'Stopp',
    'chat.mikro': 'Sprechen',
    'chat.neu': 'Neues Gespräch',
    'chat.einstellungen': 'Einstellungen',
    'chat.leer': '{name} wartet. Schreib etwas oder drück {hotkey} zum Sprechen.',
    'chat.hoert': '{name} hört zu …',
    'chat.denkt': '{name} arbeitet …',
    'chat.freigabe': 'Freigabe nötig',
    'chat.auftrag': 'Auftrag freigeben (zupackend)',
    'chat.auftrag_kategorien': 'Deckt ab',
    'chat.ja': 'Ja, machen',
    'chat.nein': 'Nein',
    'chat.freigegeben': 'Freigegeben',
    'chat.abgelehnt': 'Abgelehnt',
    'chat.kein_schluessel': 'Es ist noch kein API-Schlüssel hinterlegt. Öffne die Einstellungen und trag ihn ein.',
    'chat.abgebrochen': 'Abgebrochen.',
    'chat.fehler': 'Fehler',
    'chat.beschaeftigt': '{name} ist noch mit dem letzten Auftrag beschäftigt. Stopp drücken, um ihn abzubrechen.',
    'chat.du': 'Du',
    'chat.sprache': 'per Sprache',
    'hinweis.verweigert': 'Das kann ich nicht übernehmen.',
    'hinweis.max_tokens': 'Die Antwort wurde am Längenlimit abgeschnitten.',
    'hinweis.zu_viele_runden': 'Nach 60 Arbeitsschritten angehalten. Sag Bescheid, wenn ich weitermachen soll.',

    'einst.titel': '{name} – Einstellungen',
    'einst.einrichtung_titel': 'Willkommen. Einmal kurz einrichten.',
    'einst.einrichtung_text': '{name} braucht deinen Vornamen, einen KI-Anbieter (API-Schlüssel oder lokales Modell) und die Ordner, in denen ohne Rückfrage Dateien angelegt und geändert werden dürfen. Alles lässt sich später ändern.',
    'einst.assistent_name': 'Name deiner KI',
    'einst.assistent_form': 'Form',
    'einst.form_weiblich': 'Assistentin (sie)',
    'einst.form_maennlich': 'Assistent (er)',
    'einst.form_neutral': 'neutral (KI)',
    'einst.pronomen': 'Deine Pronomen',
    'einst.pronomen_er': 'er/ihm',
    'einst.pronomen_sie': 'sie/ihr',
    'einst.pronomen_neutral': 'keine – nur mein Name',
    'einst.pronomen_eigene': 'eigene …',
    'einst.pronomen_eigen': 'Deine eigenen Pronomen',
    'einst.allgemein': 'Allgemein',
    'einst.sprachcode': 'Sprache',
    'einst.name': 'Dein Vorname',
    'einst.schluessel': 'API-Schlüssel – {anbieter}',
    'einst.schluessel_holen': 'Schlüssel holen',
    'einst.anbieter': 'KI-Anbieter',
    'einst.anbieter_url': 'Adresse der Schnittstelle',
    'einst.anbieter_abo': 'Claude-Abo über Claude Code (nur für den eigenen Gebrauch)',
    'einst.abo_hinweis': 'Nutzt dein installiertes Claude Code mit deinem Claude-Abo – ohne API-Schlüssel und ohne API-Kosten. Nur für den eigenen Gebrauch: Anthropic erlaubt es nicht, Abo-Zugänge in fremden Produkten anzubieten. Claude Codes eigene Werkzeuge sind abgeschaltet; {name} arbeitet nur mit den eigenen Werkzeugen, und die Ampel gilt wie immer. Einmal in Claude Code mit /login anmelden.',
    'einst.lokal_hinweis': 'Läuft auf deinem PC, ohne Schlüssel und ohne Kosten. Das Modell muss Werkzeuge aufrufen können (Tool Calling); für Screenshots braucht es eines, das Bilder versteht.',
    'einst.fremd_hinweis': 'Geht mit jedem Modell, das Werkzeuge aufrufen kann (Tool Calling); für Screenshots braucht es eines, das Bilder versteht. Eine Websuche gibt es nur mit Claude – hier liest {name} Webseiten, deren Adresse bekannt ist.',
    'einst.modelle_laden': 'Modelle laden',
    'einst.modelle_geladen': '{anzahl} Modelle geladen – im Feld auswählen.',
    'einst.fehlt_url': 'Bitte die Adresse der Schnittstelle eintragen.',
    'einst.fehlt_claude': 'Claude Code wurde auf diesem PC nicht gefunden.',
    'einst.schluessel_hinweis': 'Wird mit Windows verschlüsselt gespeichert und nie angezeigt.',
    'einst.schluessel_gesetzt': 'Schlüssel ist hinterlegt. Leer lassen, um ihn zu behalten.',
    'einst.modell': 'Modell',
    'einst.aufwand': 'Denkaufwand',
    'einst.ordner': 'Arbeitsverzeichnisse',
    'einst.ordner_hinweis': 'Hier darf {name} ohne Rückfrage schreiben (GRÜN). Überall sonst wird vorher gefragt.',
    'einst.ordner_hinzu': 'Ordner hinzufügen …',
    'einst.entfernen': 'Entfernen',
    'einst.sprache': 'Sprache und Hotkeys',
    'einst.hotkey_sprechen': 'Hotkey Sprechen',
    'einst.hotkey_chat': 'Hotkey Chat',
    'einst.vorlesen': 'Antworten vorlesen',
    'einst.vorlesen_bei': 'wenn ich gesprochen habe',
    'einst.vorlesen_immer': 'immer',
    'einst.vorlesen_nie': 'nie',
    'einst.stimme': 'Stimme',
    'einst.sprechtempo': 'Sprechtempo',
    'einst.blase': 'Blase',
    'einst.blase_an': 'Blase anzeigen',
    'einst.monitor': 'Monitor',
    'einst.groesse': 'Größe (px)',
    'einst.ecke': 'Ecke',
    'einst.deckkraft': 'Deckkraft',
    'einst.tempo': 'Tempo',
    'einst.empfindlichkeit': 'Empfindlichkeit',
    'einst.farben': 'Farben je Zustand (Hex, mit Komma getrennt)',
    'einst.standardfarben': 'Standardfarben',
    'einst.system': 'System und Updates',
    'einst.autostart': 'Mit Windows starten',
    'einst.update_pruefen': 'Beim Start nach Updates sehen',
    'einst.update_auto': 'Updates ohne Rückfrage einspielen',
    'einst.update_kanal': 'Update-Kanal',
    'einst.kanal_stabil': 'stabil',
    'einst.kanal_test': 'test (auch Vorabversionen)',
    'einst.speichern': 'Speichern',
    'einst.fertig': 'Los geht\'s',
    'einst.gespeichert': 'Gespeichert.',
    'einst.fehlt_name': 'Bitte einen Vornamen eintragen.',
    'einst.fehlt_schluessel': 'Bitte einen API-Schlüssel eintragen.',
    'einst.version': 'Version',
    'design.titel': 'Design',
    'design.modus': 'Modus',
    'design.dunkel': 'Dunkel',
    'design.hell': 'Hell',
    'design.system': 'Wie Windows',
    'design.akzent': 'Akzentfarbe',
    'design.eigene': 'Eigene',
    'design.glow': 'Leuchteffekte',
    'design.blase_akzent': 'Blase an Akzentfarbe anpassen',
    'design.p.glut': 'Glut',
    'design.p.neon': 'Neon',
    'design.p.cyber': 'Cyber',
    'design.p.toxic': 'Toxic',
    'design.p.magenta': 'Magenta',
    'design.p.blut': 'Blut',
    'design.p.gold': 'Gold',
    'konten.titel': 'Verbindungen',
    'konten.hinweis': 'Konten, die {name} für dich nutzen darf. Anmelden tust du selbst im Browser – {name} sieht nie ein Passwort.',
    'konten.google_text': 'Gmail, Kalender und Kontakte. Einmalig nötig: ein eigener OAuth-Client aus der Google Cloud Console.',
    'konten.anleitung': 'Anleitung öffnen',
    'konten.client_id': 'Client-ID',
    'konten.client_secret': 'Client-Secret',
    'konten.verbinden': 'Mit Google verbinden',
    'konten.trennen': 'Trennen',
    'konten.verbunden_als': 'Verbunden als {email}',
    'konten.nicht_verbunden': 'Nicht verbunden',
    'konten.warte_browser': 'Der Browser ist offen – melde dich dort an und erlaube den Zugriff …',
    'konten.secret_gespeichert': 'Secret ist gespeichert. Leer lassen, um es zu behalten.',
    'chat.handy': 'vom Handy',
    'handy.titel': 'Handy im WLAN',
    'handy.text': 'Schreib {name} vom Handy aus, solange es im selben WLAN ist – im Browser, ohne App und ohne Cloud. Die Verbindung ist verschlüsselt, und nur das gekoppelte Handy kommt rein. Freigaben beantwortest du dort mit Ja oder Nein, ROT bleibt ROT.',
    'handy.an': 'Handy im WLAN erlauben',
    'handy.aus': 'Aus',
    'handy.bereit': 'Bereit – noch kein Handy gekoppelt',
    'handy.gekoppelt': 'Gekoppelt: {geraet}',
    'handy.koppeln': 'Handy koppeln',
    'handy.neu_koppeln': 'Anderes Handy koppeln',
    'handy.qr_text': 'Scanne den Code mit der Handy-Kamera. Er gilt fünf Minuten und nur einmal; ein neu gekoppeltes Handy ersetzt das alte.',
    'handy.warnung': 'Beim ersten Öffnen warnt der Browser, weil das Zertifikat von {name} selbst stammt. Vergleiche in den Zertifikatsdetails den SHA-256-Fingerabdruck mit diesem hier und fahre erst dann fort:',
    'handy.firewall': 'Fragt Windows nach der Firewall, erlaube nur „Private Netzwerke“.',
    'handy.port': 'Port',
    'handy.fehler_port': 'Port {port} ist schon belegt – wähle unten einen anderen.',
    'handy.kein_netz': 'Kein WLAN oder Netzwerk gefunden. Ist der PC mit dem Heimnetz verbunden?',
    'mobil.platzhalter': 'Schreib {name} etwas …',
    'mobil.senden': 'Senden',
    'mobil.stopp': 'Stopp',
    'mobil.neu': 'Neues Gespräch',
    'mobil.wartet': 'wartet',
    'mobil.arbeitet': 'arbeitet …',
    'mobil.leer': 'Schreib {name}, was am PC passieren soll. Bevor etwas Wichtiges passiert, fragt {name} dich hier.',
    'mobil.am_pc': 'am PC',
    'mobil.freigabe': 'Freigabe nötig',
    'mobil.auftrag': 'Auftrag freigeben',
    'mobil.ja': 'Ja, machen',
    'mobil.nein': 'Nein',
    'mobil.freigegeben': 'Freigegeben',
    'mobil.abgelehnt': 'Abgelehnt',
    'mobil.beschaeftigt': '{name} arbeitet noch. Tippe auf Stopp, um abzubrechen.',
    'mobil.offline': 'Keine Verbindung zum PC – ich versuche es weiter …',
    'mobil.koppeln': 'Dieses Handy ist noch nicht gekoppelt. Öffne am PC Einstellungen → Verbindungen → Handy im WLAN und scanne den QR-Code.',
    'mobil.code_falsch': 'Der Code ist abgelaufen oder schon benutzt. Erzeuge am PC einen neuen QR-Code.',
    'mobil.getrennt': 'Dieses Handy wurde am PC getrennt. Koppel es neu, um weiterzuschreiben.',
    'mobil.gesperrt': 'Zu viele Fehlversuche. Warte zehn Minuten.',
    'nav.start': 'Start',
    'nav.chat': 'Chat',
    'nav.einstellungen': 'Einstellungen',
    'start.gruss_morgen': 'Guten Morgen',
    'start.gruss_tag': 'Hallo',
    'start.gruss_abend': 'Guten Abend',
    'start.gruss_nacht': 'Noch wach',
    'start.unter': '{name} ist bereit. Was steht an?',
    'start.platzhalter': 'Frag {name} etwas …',
    'start.briefing': 'Tagesbriefing',
    'start.briefing_frage': 'Gib mir ein kurzes Briefing für heute: Termine, wichtige ungelesene Mails, offene Erinnerungen und wie es dem PC geht. Nach Wichtigkeit sortiert, kurz.',
    'start.v1': 'Was mache ich hier gerade?',
    'start.v2': 'Räum meinen Downloads-Ordner auf',
    'start.v3': 'Erinner mich in 30 Minuten an eine Pause',
    'start.v4': 'Welche Programme starten mit Windows?',
    'start.termine': 'Termine',
    'start.heute': 'Heute',
    'start.morgen': 'Morgen',
    'start.ganztaegig': 'ganztags',
    'start.keine_termine': 'Heute und morgen steht nichts im Kalender.',
    'start.aktion_termine': 'Tag planen',
    'start.frage_termine': 'Schau dir meine Termine für heute und morgen an und hilf mir, den Tag zu planen.',
    'start.mails': 'Posteingang',
    'start.ungelesen': 'ungelesen',
    'start.keine_mails': 'Keine ungelesenen Mails.',
    'start.aktion_mails': 'Zusammenfassen',
    'start.frage_mails': 'Fass meine ungelesenen Mails kurz zusammen – was ist wichtig, was kann warten?',
    'start.google_hinweis': 'Verbinde Google, dann siehst du hier Termine und Mails.',
    'start.google_verbinden': 'Google verbinden',
    'start.erinnerungen': 'Erinnerungen',
    'start.keine_erinnerungen': 'Nichts geplant. Sag einfach „Erinner mich um …“.',
    'start.gleich': 'gleich',
    'start.in_min': 'in {n} Min',
    'start.pc': 'Dieser PC',
    'start.aktion_pc': 'Prüfen',
    'start.frage_pc': 'Schau nach, wie es meinem PC geht: Was frisst gerade Arbeitsspeicher und CPU, und ist irgendwo die Platte knapp?',
    'start.akku': 'Akku',
    'start.netz': 'am Netz',
    'start.ram': 'Arbeitsspeicher',
    'start.platte': 'Laufwerk {lw}',
    'start.frei': '{gb} GB frei',
    'start.kosten': 'Kosten heute',
    'start.kosten_lokal': 'Kostenlos – das Modell läuft lokal oder über dein Abo.',
    'start.anfragen': '{n} Anfragen',
    'start.limit': 'Tageslimit',
    'start.von_limit': 'von {limit} US-$',
    'start.fehler': 'Gerade nicht erreichbar.',
    'start.aktualisieren': 'Aktualisieren',
    'start.stand': 'Stand {zeit}',
    'nav.verlauf': 'Verlauf',
    'vl.suche': 'Gespräche durchsuchen …',
    'vl.leer': 'Noch keine gespeicherten Gespräche.',
    'vl.keine_treffer': 'Nichts gefunden für „{suche}“.',
    'vl.waehlen': 'Wähl links ein Gespräch aus.',
    'vl.ohne_titel': 'Gespräch',
    'vl.fortsetzen': 'Fortsetzen',
    'vl.loeschen': 'Löschen',
    'vl.sicher': 'Wirklich löschen?',
    'vl.alle_loeschen': 'Alle löschen',
    'vl.alle_sicher': 'Wirklich alle löschen?',
    'vl.heute': 'Heute',
    'vl.gestern': 'Gestern',
    'vl.woche': 'Diese Woche',
    'vl.aelter': 'Älter',
    'vl.aus': 'Neue Gespräche werden gerade nicht gespeichert. Einschalten unter Einstellungen → System.',
    'vl.beschaeftigt': '{name} arbeitet gerade. Erst danach ein altes Gespräch fortsetzen.',
    'vl.fortgesetzt': 'Gespräch vom {datum} fortgesetzt. Weil darin fremde Inhalte gewesen sein können, fragt {name} vor Links und Aktionen nach außen.',
    'einst.verlauf_speichern': 'Gespräche speichern (verschlüsselt, nur auf diesem PC, ohne Screenshots)',
    'nav.routinen': 'Routinen',
    'start.schnell': 'Schnellaktionen',
    'rt.hinweis': 'Eigene Abläufe auf Knopfdruck. Beim Start legt {name} dir den ganzen Ablauf einmal zur Freigabe vor – danach laufen die Schritte ohne Einzelfrage. Die Freigabe gilt nur für diesen Durchlauf, ROT bleibt ROT.',
    'rt.neu': 'Neue Routine',
    'rt.name': 'Name',
    'rt.symbol': 'Symbol',
    'rt.schritte': 'Schritte – einer pro Zeile, in deinen Worten',
    'rt.platzhalter_schritte': 'Öffne Steam\nÖffne Discord\nSag mir, wie viel Arbeitsspeicher frei ist',
    'rt.speichern': 'Speichern',
    'rt.abbrechen': 'Abbrechen',
    'rt.starten': 'Starten',
    'rt.bearbeiten': 'Bearbeiten',
    'rt.loeschen': 'Löschen',
    'rt.sicher': 'Sicher?',
    'rt.anzahl': '{n} Schritte',
    'rt.leer': 'Noch keine Routinen. Leg eine an – zum Beispiel „Feierabend“.',
    'rt.fehler_name': 'Bitte einen Namen mit höchstens 40 Zeichen eingeben.',
    'rt.fehler_schritte': 'Bitte mindestens einen Schritt eintragen.',
    'rt.fehler_lang': 'Höchstens 12 Schritte mit je bis zu 300 Zeichen.',
    'rt.fehler_viele': 'Mehr als 30 Routinen gehen nicht.',
    'rt.fehlt': 'Diese Routine gibt es nicht mehr.',
    'rt.nachricht': 'Führe meine Routine „{routine}“ aus. Leg mir zuerst mit auftrag_vorlegen den ganzen Ablauf einmal zur Freigabe vor (gilt nur für diesen Durchlauf), arbeite dann die Schritte der Reihe nach ab und sag am Ende kurz, was gelaufen ist. Wenn ein Schritt nur GRÜN ist, brauchst du dafür keine Kategorie.\n{schritte}',
    'chat.anhaengen': 'Dateien anhängen',
    'chat.ablegen': 'Dateien hier ablegen',
    'chat.nur_dateien': 'Schau dir das an.',
    'chat.kopieren': 'Kopieren',
    'chat.kopiert': 'Kopiert',
    'einst.hotkey_auswahl': 'Hotkey markierter Text',
    'aw.titel': 'Markierter Text',
    'aw.frage': 'Eigene Frage dazu …',
    'aw.nichts': 'Kein Text markiert. Markier etwas und drück den Hotkey noch mal.',
    'aw.a_uebersetzen': 'Übersetzen',
    'aw.a_zusammenfassen': 'Zusammenfassen',
    'aw.a_umformulieren': 'Umformulieren',
    'aw.a_erklaeren': 'Erklären',
    'aw.a_korrigieren': 'Fehler korrigieren',
    'aw.a_antworten': 'Antwort entwerfen',
    'aw.f_uebersetzen': 'Übersetze den markierten Text: ins Deutsche, oder ins Englische, wenn er schon Deutsch ist. Nur die Übersetzung.',
    'aw.f_zusammenfassen': 'Fass den markierten Text in drei bis fünf Sätzen zusammen.',
    'aw.f_umformulieren': 'Formulier den markierten Text klarer und freundlicher um. Nur die neue Fassung.',
    'aw.f_erklaeren': 'Erklär mir den markierten Text einfach und kurz.',
    'aw.f_korrigieren': 'Korrigier Rechtschreibung und Grammatik im markierten Text. Nur die korrigierte Fassung.',
    'aw.f_antworten': 'Entwirf eine kurze, freundliche Antwort auf den markierten Text. Nur den Entwurf – nichts senden.',
    'aw.nutzer': '✂ Markierter Text: {aktion}',
    'einst.blase_untertitel': 'Untertitel unter der Blase – was du sagst und die Antwort',
    'einst.blase_zieh_hinweis': 'Die Blase lässt sich mit der Maus überallhin ziehen, Doppelklick öffnet den Chat.',
    'einst.blase_position': 'Position zurücksetzen',
    'blase.hoert': 'Ich höre zu …',
    'blase.freigabe': 'Freigabe nötig – bitte im Chat bestätigen.',
    'ecke.unten-rechts': 'unten rechts',
    'ecke.unten-links': 'unten links',
    'ecke.oben-rechts': 'oben rechts',
    'ecke.oben-links': 'oben links',
    'monitor.0': 'Hauptmonitor',
    'monitor.n': 'Monitor {n}',
    'zustand.idle': 'wartet',
    'zustand.listening': 'hört zu',
    'zustand.thinking': 'denkt',
    'zustand.speaking': 'spricht',

    'update.titel': '{name}-Update',
    'update.aktuell': '{name} ist aktuell (Version {version}).',
    'update.neu': 'Version {neu} ist verfügbar (du hast {alt}).',
    'update.frage': 'Jetzt einspielen? {name} startet dabei neu.',
    'update.einspielen': 'Einspielen',
    'update.spaeter': 'Später',
    'update.wartet': 'Das Update wird eingespielt, sobald die laufende Aufgabe fertig ist.',
    'update.fehler': 'Update-Prüfung fehlgeschlagen: {fehler}',
    'update.erfolg': '{name} wurde auf {version} aktualisiert.',
    'update.zurueck': 'Das Update auf {version} ist fehlgeschlagen, {name} läuft wieder auf dem vorherigen Stand. {fehler}',
    'update.verfuegbar_hinweis': 'Update auf {version} verfügbar. Tray-Menü → Nach Updates suchen.',

    'hotkey.fehler': 'Der Hotkey {hotkey} ist schon belegt. In den Einstellungen einen anderen wählen.',
  },

  en: {
    'tray.tooltip': '{name}',
    'tray.chat': 'Open chat',
    'tray.sprechen': 'Talk',
    'tray.overlay': 'Toggle overlay',
    'einst.tageslimit': 'Cost brake: daily limit in US$ (0 = off)',
    'einst.kosten_heute': 'So far today: {usd} US$ in {anfragen} requests (estimated at list price).',
    'hinweis.kosten_warnung': "80 % of today's cost limit is already used.",
    'protokoll.verletzt': 'The log was changed after the fact (line {zeile}). Please check who touched protokoll.jsonl.',
    'tray.weckwort': 'Listen for "Hey {name}"',
    'tray.tooltip_weckwort': '{name} – listening for "Hey {name}"',
    'einst.weckwort': 'Listen for "Hey {name}"',
    'einst.weckwort_hinweis': 'The microphone stays open for this. Only the wake word is detected, right on the PC – nothing is recorded or sent. It pauses while {name} is listening or speaking.',
    'einst.weckwort_schwelle': 'Detection threshold',
    'weckwort.kein_mikrofon': '"Hey {name}" needs a microphone. Please connect one or pick it as the default recording device in the Windows sound settings, then turn the wake word on again.',
    'weckwort.fehler': 'For "Hey {name}", Windows needs speech recognition for {sprache}. Please add it under Settings → Time & language → Language.',
    'erinnerung.titel': '⏰ Reminder',
    'erinnerung.verspaetet': 'Missed (was due at {zeit}): {text}',
    'einst.erinnerung_vorlesen': 'Read reminders aloud',
    'chat.schliessen': 'Close',
    'einst.overlay': 'Overlay (gaming)',
    'einst.overlay_hinweis': 'A small chat window over games in windowed or borderless fullscreen. With exclusive fullscreen, Windows shows no overlays. Leave the hotkey empty to turn it off.',
    'einst.hotkey_overlay': 'Overlay hotkey',
    'einst.overlay_deckkraft': 'Opacity',
    'einst.overlay_bei_antwort': 'On voice commands',
    'einst.overlay_aus': "don't show anything",
    'einst.overlay_passiv': 'briefly show the answer (click-through)',
    'tray.blase': 'Show orb',
    'tray.einstellungen': 'Settings …',
    'tray.neu': 'New conversation',
    'tray.updates': 'Check for updates',
    'tray.protokoll': 'Open log',
    'tray.beenden': 'Quit',

    'chat.titel': '{name}',
    'chat.platzhalter': 'Write to {name} …',
    'chat.senden': 'Send',
    'chat.stopp': 'Stop',
    'chat.mikro': 'Talk',
    'chat.neu': 'New conversation',
    'chat.einstellungen': 'Settings',
    'chat.leer': '{name} is waiting. Type something or press {hotkey} to talk.',
    'chat.hoert': '{name} is listening …',
    'chat.denkt': '{name} is working …',
    'chat.freigabe': 'Approval needed',
    'chat.auftrag': 'Approve task (hands-on)',
    'chat.auftrag_kategorien': 'Covers',
    'chat.ja': 'Yes, do it',
    'chat.nein': 'No',
    'chat.freigegeben': 'Approved',
    'chat.abgelehnt': 'Declined',
    'chat.kein_schluessel': 'No API key yet. Open the settings and enter it.',
    'chat.abgebrochen': 'Stopped.',
    'chat.fehler': 'Error',
    'chat.beschaeftigt': '{name} is still busy with the last task. Press Stop to cancel it.',
    'chat.du': 'You',
    'chat.sprache': 'by voice',
    'hinweis.verweigert': 'I can\'t take that on.',
    'hinweis.max_tokens': 'The answer was cut off at the length limit.',
    'hinweis.zu_viele_runden': 'Stopped after 60 steps. Tell me if I should carry on.',

    'einst.titel': '{name} – Settings',
    'einst.einrichtung_titel': 'Welcome. Quick one-time setup.',
    'einst.einrichtung_text': '{name} needs your first name, an AI provider (API key or local model) and the folders where files may be created and changed without asking. Everything can be changed later.',
    'einst.assistent_name': "Your AI's name",
    'einst.assistent_form': 'Form',
    'einst.form_weiblich': 'assistant (she)',
    'einst.form_maennlich': 'assistant (he)',
    'einst.form_neutral': 'neutral (they)',
    'einst.pronomen': 'Your pronouns',
    'einst.pronomen_er': 'he/him',
    'einst.pronomen_sie': 'she/her',
    'einst.pronomen_neutral': 'none – just my name',
    'einst.pronomen_eigene': 'custom …',
    'einst.pronomen_eigen': 'Your custom pronouns',
    'einst.allgemein': 'General',
    'einst.sprachcode': 'Language',
    'einst.name': 'Your first name',
    'einst.schluessel': 'API key – {anbieter}',
    'einst.schluessel_holen': 'Get a key',
    'einst.anbieter': 'AI provider',
    'einst.anbieter_url': 'API address',
    'einst.anbieter_abo': 'Claude subscription via Claude Code (personal use only)',
    'einst.abo_hinweis': 'Uses your installed Claude Code with your Claude subscription – no API key and no API costs. Personal use only: Anthropic does not allow offering subscription access in third-party products. Claude Code\'s own tools are switched off; {name} uses only the app’s own tools, and the traffic light applies as always. Sign in once in Claude Code with /login.',
    'einst.lokal_hinweis': 'Runs on your PC, no key and no costs. The model must support tool calling; for screenshots it needs to understand images.',
    'einst.fremd_hinweis': 'Works with any model that supports tool calling; for screenshots it needs one that understands images. Web search is only available with Claude – here {name} reads web pages whose address is known.',
    'einst.modelle_laden': 'Load models',
    'einst.modelle_geladen': '{anzahl} models loaded – pick one in the field.',
    'einst.fehlt_url': 'Please enter the API address.',
    'einst.fehlt_claude': 'Claude Code was not found on this PC.',
    'einst.schluessel_hinweis': 'Stored encrypted by Windows and never shown again.',
    'einst.schluessel_gesetzt': 'A key is stored. Leave empty to keep it.',
    'einst.modell': 'Model',
    'einst.aufwand': 'Thinking effort',
    'einst.ordner': 'Working directories',
    'einst.ordner_hinweis': '{name} may write here without asking (GREEN). Everywhere else, {name} asks first.',
    'einst.ordner_hinzu': 'Add folder …',
    'einst.entfernen': 'Remove',
    'einst.sprache': 'Voice and hotkeys',
    'einst.hotkey_sprechen': 'Talk hotkey',
    'einst.hotkey_chat': 'Chat hotkey',
    'einst.vorlesen': 'Read answers aloud',
    'einst.vorlesen_bei': 'when I spoke',
    'einst.vorlesen_immer': 'always',
    'einst.vorlesen_nie': 'never',
    'einst.stimme': 'Voice',
    'einst.sprechtempo': 'Speech rate',
    'einst.blase': 'Orb',
    'einst.blase_an': 'Show orb',
    'einst.monitor': 'Monitor',
    'einst.groesse': 'Size (px)',
    'einst.ecke': 'Corner',
    'einst.deckkraft': 'Opacity',
    'einst.tempo': 'Speed',
    'einst.empfindlichkeit': 'Sensitivity',
    'einst.farben': 'Colours per state (hex, comma separated)',
    'einst.standardfarben': 'Default colours',
    'einst.system': 'System and updates',
    'einst.autostart': 'Start with Windows',
    'einst.update_pruefen': 'Check for updates on start',
    'einst.update_auto': 'Install updates without asking',
    'einst.update_kanal': 'Update channel',
    'einst.kanal_stabil': 'stable',
    'einst.kanal_test': 'test (includes pre-releases)',
    'einst.speichern': 'Save',
    'einst.fertig': 'Let\'s go',
    'einst.gespeichert': 'Saved.',
    'einst.fehlt_name': 'Please enter a first name.',
    'einst.fehlt_schluessel': 'Please enter an API key.',
    'einst.version': 'Version',
    'design.titel': 'Design',
    'design.modus': 'Mode',
    'design.dunkel': 'Dark',
    'design.hell': 'Light',
    'design.system': 'Like Windows',
    'design.akzent': 'Accent colour',
    'design.eigene': 'Custom',
    'design.glow': 'Glow effects',
    'design.blase_akzent': 'Match orb to accent colour',
    'design.p.glut': 'Ember',
    'design.p.neon': 'Neon',
    'design.p.cyber': 'Cyber',
    'design.p.toxic': 'Toxic',
    'design.p.magenta': 'Magenta',
    'design.p.blut': 'Blood',
    'design.p.gold': 'Gold',
    'konten.titel': 'Connections',
    'konten.hinweis': 'Accounts {name} may use for you. You sign in yourself in the browser – {name} never sees a password.',
    'konten.google_text': 'Gmail, Calendar and Contacts. Needed once: your own OAuth client from the Google Cloud Console.',
    'konten.anleitung': 'Open guide',
    'konten.client_id': 'Client ID',
    'konten.client_secret': 'Client secret',
    'konten.verbinden': 'Connect Google',
    'konten.trennen': 'Disconnect',
    'konten.verbunden_als': 'Connected as {email}',
    'konten.nicht_verbunden': 'Not connected',
    'konten.warte_browser': 'The browser is open – sign in there and allow access …',
    'konten.secret_gespeichert': 'Secret is stored. Leave empty to keep it.',
    'chat.handy': 'from phone',
    'handy.titel': 'Phone on Wi-Fi',
    'handy.text': 'Message {name} from your phone while it is on the same Wi-Fi – in the browser, no app, no cloud. The connection is encrypted and only the paired phone gets in. You answer approvals there with yes or no; RED stays RED.',
    'handy.an': 'Allow phone on Wi-Fi',
    'handy.aus': 'Off',
    'handy.bereit': 'Ready – no phone paired yet',
    'handy.gekoppelt': 'Paired: {geraet}',
    'handy.koppeln': 'Pair phone',
    'handy.neu_koppeln': 'Pair another phone',
    'handy.qr_text': 'Scan the code with your phone camera. It is valid for five minutes and only once; a newly paired phone replaces the old one.',
    'handy.warnung': 'The first time, the browser warns because the certificate comes from {name} itself. Compare the SHA-256 fingerprint in the certificate details with this one and only then continue:',
    'handy.firewall': 'If Windows asks about the firewall, allow "Private networks" only.',
    'handy.port': 'Port',
    'handy.fehler_port': 'Port {port} is already in use – pick another one below.',
    'handy.kein_netz': 'No Wi-Fi or network found. Is the PC connected to your home network?',
    'mobil.platzhalter': 'Write to {name} …',
    'mobil.senden': 'Send',
    'mobil.stopp': 'Stop',
    'mobil.neu': 'New conversation',
    'mobil.wartet': 'idle',
    'mobil.arbeitet': 'working …',
    'mobil.leer': 'Tell {name} what should happen on the PC. Before anything important happens, {name} asks you here.',
    'mobil.am_pc': 'on the PC',
    'mobil.freigabe': 'Approval needed',
    'mobil.auftrag': 'Approve task',
    'mobil.ja': 'Yes, do it',
    'mobil.nein': 'No',
    'mobil.freigegeben': 'Approved',
    'mobil.abgelehnt': 'Declined',
    'mobil.beschaeftigt': '{name} is still working. Tap Stop to cancel.',
    'mobil.offline': 'No connection to the PC – still trying …',
    'mobil.koppeln': 'This phone is not paired yet. On the PC open Settings → Connections → Phone on Wi-Fi and scan the QR code.',
    'mobil.code_falsch': 'The code has expired or was already used. Create a new QR code on the PC.',
    'mobil.getrennt': 'This phone was disconnected on the PC. Pair it again to keep writing.',
    'mobil.gesperrt': 'Too many failed attempts. Wait ten minutes.',
    'nav.start': 'Home',
    'nav.chat': 'Chat',
    'nav.einstellungen': 'Settings',
    'start.gruss_morgen': 'Good morning',
    'start.gruss_tag': 'Hi',
    'start.gruss_abend': 'Good evening',
    'start.gruss_nacht': 'Still up',
    'start.unter': '{name} is ready. What’s up?',
    'start.platzhalter': 'Ask {name} anything …',
    'start.briefing': 'Daily briefing',
    'start.briefing_frage': 'Give me a short briefing for today: events, important unread mail, open reminders and how the PC is doing. Sorted by importance, short.',
    'start.v1': 'What am I doing here?',
    'start.v2': 'Tidy up my Downloads folder',
    'start.v3': 'Remind me to take a break in 30 minutes',
    'start.v4': 'Which programs start with Windows?',
    'start.termine': 'Events',
    'start.heute': 'Today',
    'start.morgen': 'Tomorrow',
    'start.ganztaegig': 'all day',
    'start.keine_termine': 'Nothing in the calendar today or tomorrow.',
    'start.aktion_termine': 'Plan day',
    'start.frage_termine': 'Look at my events for today and tomorrow and help me plan the day.',
    'start.mails': 'Inbox',
    'start.ungelesen': 'unread',
    'start.keine_mails': 'No unread mail.',
    'start.aktion_mails': 'Summarise',
    'start.frage_mails': 'Briefly summarise my unread mail – what matters, what can wait?',
    'start.google_hinweis': 'Connect Google to see events and mail here.',
    'start.google_verbinden': 'Connect Google',
    'start.erinnerungen': 'Reminders',
    'start.keine_erinnerungen': 'Nothing planned. Just say "Remind me at …".',
    'start.gleich': 'now',
    'start.in_min': 'in {n} min',
    'start.pc': 'This PC',
    'start.aktion_pc': 'Check',
    'start.frage_pc': 'Check how my PC is doing: what is eating memory and CPU right now, and is any disk running low?',
    'start.akku': 'Battery',
    'start.netz': 'plugged in',
    'start.ram': 'Memory',
    'start.platte': 'Drive {lw}',
    'start.frei': '{gb} GB free',
    'start.kosten': 'Cost today',
    'start.kosten_lokal': 'Free – the model runs locally or via your subscription.',
    'start.anfragen': '{n} requests',
    'start.limit': 'Daily limit',
    'start.von_limit': 'of {limit} US$',
    'start.fehler': 'Not reachable right now.',
    'start.aktualisieren': 'Refresh',
    'start.stand': 'As of {zeit}',
    'nav.verlauf': 'History',
    'vl.suche': 'Search conversations …',
    'vl.leer': 'No saved conversations yet.',
    'vl.keine_treffer': 'Nothing found for "{suche}".',
    'vl.waehlen': 'Pick a conversation on the left.',
    'vl.ohne_titel': 'Conversation',
    'vl.fortsetzen': 'Continue',
    'vl.loeschen': 'Delete',
    'vl.sicher': 'Really delete?',
    'vl.alle_loeschen': 'Delete all',
    'vl.alle_sicher': 'Really delete all?',
    'vl.heute': 'Today',
    'vl.gestern': 'Yesterday',
    'vl.woche': 'This week',
    'vl.aelter': 'Older',
    'vl.aus': 'New conversations are not being saved right now. Turn it on under Settings → System.',
    'vl.beschaeftigt': '{name} is busy. Continue an old conversation afterwards.',
    'vl.fortgesetzt': 'Continued the conversation from {datum}. Since it may have contained foreign content, {name} asks before links and outward actions.',
    'einst.verlauf_speichern': 'Save conversations (encrypted, only on this PC, no screenshots)',
    'nav.routinen': 'Routines',
    'start.schnell': 'Quick actions',
    'rt.hinweis': 'Your own workflows at the push of a button. When started, {name} shows you the whole workflow once for approval – then the steps run without asking each time. The approval covers only this run; RED stays RED.',
    'rt.neu': 'New routine',
    'rt.name': 'Name',
    'rt.symbol': 'Icon',
    'rt.schritte': 'Steps – one per line, in your own words',
    'rt.platzhalter_schritte': 'Open Steam\nOpen Discord\nTell me how much memory is free',
    'rt.speichern': 'Save',
    'rt.abbrechen': 'Cancel',
    'rt.starten': 'Run',
    'rt.bearbeiten': 'Edit',
    'rt.loeschen': 'Delete',
    'rt.sicher': 'Sure?',
    'rt.anzahl': '{n} steps',
    'rt.leer': 'No routines yet. Create one – for example "End of day".',
    'rt.fehler_name': 'Please enter a name of up to 40 characters.',
    'rt.fehler_schritte': 'Please enter at least one step.',
    'rt.fehler_lang': 'At most 12 steps of up to 300 characters each.',
    'rt.fehler_viele': 'No more than 30 routines.',
    'rt.fehlt': 'This routine no longer exists.',
    'rt.nachricht': 'Run my routine "{routine}". First present the whole workflow once for approval with auftrag_vorlegen (valid only for this run), then work through the steps in order and briefly say at the end what ran. Steps that are only GREEN need no category.\n{schritte}',
    'chat.anhaengen': 'Attach files',
    'chat.ablegen': 'Drop files here',
    'chat.nur_dateien': 'Take a look at this.',
    'chat.kopieren': 'Copy',
    'chat.kopiert': 'Copied',
    'einst.hotkey_auswahl': 'Marked text hotkey',
    'aw.titel': 'Marked text',
    'aw.frage': 'Ask your own question …',
    'aw.nichts': 'No text marked. Mark something and press the hotkey again.',
    'aw.a_uebersetzen': 'Translate',
    'aw.a_zusammenfassen': 'Summarise',
    'aw.a_umformulieren': 'Rephrase',
    'aw.a_erklaeren': 'Explain',
    'aw.a_korrigieren': 'Fix mistakes',
    'aw.a_antworten': 'Draft a reply',
    'aw.f_uebersetzen': 'Translate the marked text: into English, or into German if it is already English. Only the translation.',
    'aw.f_zusammenfassen': 'Summarise the marked text in three to five sentences.',
    'aw.f_umformulieren': 'Rephrase the marked text to be clearer and friendlier. Only the new version.',
    'aw.f_erklaeren': 'Explain the marked text to me simply and briefly.',
    'aw.f_korrigieren': 'Fix spelling and grammar in the marked text. Only the corrected version.',
    'aw.f_antworten': 'Draft a short, friendly reply to the marked text. Only the draft – send nothing.',
    'aw.nutzer': '✂ Marked text: {aktion}',
    'einst.blase_untertitel': 'Captions under the orb – what you say and the answer',
    'einst.blase_zieh_hinweis': 'Drag the orb anywhere with the mouse; double-click opens the chat.',
    'einst.blase_position': 'Reset position',
    'blase.hoert': 'Listening …',
    'blase.freigabe': 'Approval needed – please confirm in the chat.',
    'ecke.unten-rechts': 'bottom right',
    'ecke.unten-links': 'bottom left',
    'ecke.oben-rechts': 'top right',
    'ecke.oben-links': 'top left',
    'monitor.0': 'Primary monitor',
    'monitor.n': 'Monitor {n}',
    'zustand.idle': 'idle',
    'zustand.listening': 'listening',
    'zustand.thinking': 'thinking',
    'zustand.speaking': 'speaking',

    'update.titel': '{name} update',
    'update.aktuell': '{name} is up to date (version {version}).',
    'update.neu': 'Version {neu} is available (you have {alt}).',
    'update.frage': 'Install now? {name} will restart.',
    'update.einspielen': 'Install',
    'update.spaeter': 'Later',
    'update.wartet': 'The update will be installed as soon as the current task is finished.',
    'update.fehler': 'Update check failed: {fehler}',
    'update.erfolg': '{name} was updated to {version}.',
    'update.zurueck': 'The update to {version} failed; {name} is back on the previous version. {fehler}',
    'update.verfuegbar_hinweis': 'Update to {version} available. Tray menu → Check for updates.',

    'hotkey.fehler': 'The hotkey {hotkey} is already taken. Pick another one in the settings.',
  },
};

function t(sprachcode, schluessel, werte) {
  const tabelle = TEXTE[sprachcode] || TEXTE.de;
  let s = tabelle[schluessel] ?? TEXTE.de[schluessel] ?? schluessel;
  if (werte) for (const [k, v] of Object.entries(werte)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

module.exports = { TEXTE, t };
