'use strict';

// Alle Texte der Oberfläche in Deutsch und Englisch. Die Sprache folgt der
// Einstellung "sprachcode".

const TEXTE = {
  de: {
    'tray.tooltip': 'Julia',
    'tray.chat': 'Chat öffnen',
    'tray.sprechen': 'Sprechen',
    'tray.blase': 'Blase anzeigen',
    'tray.einstellungen': 'Einstellungen …',
    'tray.neu': 'Neues Gespräch',
    'tray.updates': 'Nach Updates suchen',
    'tray.protokoll': 'Protokoll öffnen',
    'tray.beenden': 'Beenden',

    'chat.titel': 'Julia',
    'chat.platzhalter': 'Schreib Julia etwas …',
    'chat.senden': 'Senden',
    'chat.stopp': 'Stopp',
    'chat.mikro': 'Sprechen',
    'chat.neu': 'Neues Gespräch',
    'chat.einstellungen': 'Einstellungen',
    'chat.leer': 'Julia wartet. Schreib etwas oder drück {hotkey} zum Sprechen.',
    'chat.hoert': 'Julia hört zu …',
    'chat.denkt': 'Julia arbeitet …',
    'chat.freigabe': 'Freigabe nötig',
    'chat.auftrag': 'Auftrag freigeben (zupackend)',
    'chat.auftrag_kategorien': 'Deckt ab',
    'chat.ja': 'Ja, machen',
    'chat.nein': 'Nein',
    'chat.freigegeben': 'Freigegeben',
    'chat.abgelehnt': 'Abgelehnt',
    'chat.kein_schluessel': 'Es ist noch kein API-Schlüssel hinterlegt. Öffne die Einstellungen und trag ihn ein.',
    'chat.abgebrochen': 'Abgebrochen.',
    'chat.fehler': 'Fehler',
    'chat.beschaeftigt': 'Julia ist noch mit dem letzten Auftrag beschäftigt. Stopp drücken, um ihn abzubrechen.',
    'chat.du': 'Du',
    'chat.sprache': 'per Sprache',
    'hinweis.verweigert': 'Das kann ich nicht übernehmen.',
    'hinweis.max_tokens': 'Die Antwort wurde am Längenlimit abgeschnitten.',
    'hinweis.zu_viele_runden': 'Nach 60 Arbeitsschritten angehalten. Sag Bescheid, wenn ich weitermachen soll.',

    'einst.titel': 'Julia – Einstellungen',
    'einst.einrichtung_titel': 'Willkommen. Einmal kurz einrichten.',
    'einst.einrichtung_text': 'Julia braucht deinen Vornamen, einen API-Schlüssel von Anthropic und die Ordner, in denen sie ohne Rückfrage Dateien anlegen und ändern darf. Alles lässt sich später ändern.',
    'einst.allgemein': 'Allgemein',
    'einst.sprachcode': 'Sprache',
    'einst.name': 'Dein Vorname',
    'einst.schluessel': 'Anthropic-API-Schlüssel',
    'einst.schluessel_hinweis': 'Wird mit Windows verschlüsselt gespeichert und nie angezeigt.',
    'einst.schluessel_gesetzt': 'Schlüssel ist hinterlegt. Leer lassen, um ihn zu behalten.',
    'einst.modell': 'Modell',
    'einst.aufwand': 'Denkaufwand',
    'einst.ordner': 'Arbeitsverzeichnisse',
    'einst.ordner_hinweis': 'Hier darf Julia ohne Rückfrage schreiben (GRÜN). Überall sonst fragt sie vorher.',
    'einst.ordner_hinzu': 'Ordner hinzufügen …',
    'einst.entfernen': 'Entfernen',
    'einst.sprache': 'Sprache und Hotkeys',
    'einst.hotkey_sprechen': 'Hotkey Sprechen',
    'einst.hotkey_chat': 'Hotkey Chat',
    'einst.vorlesen': 'Antworten vorlesen',
    'einst.vorlesen_bei': 'wenn ich gesprochen habe',
    'einst.vorlesen_immer': 'immer',
    'einst.vorlesen_nie': 'nie',
    'einst.stimme': 'Stimme',
    'einst.sprechtempo': 'Sprechtempo',
    'einst.blase': 'Blase',
    'einst.blase_an': 'Blase anzeigen',
    'einst.monitor': 'Monitor',
    'einst.groesse': 'Größe (px)',
    'einst.ecke': 'Ecke',
    'einst.deckkraft': 'Deckkraft',
    'einst.tempo': 'Tempo',
    'einst.empfindlichkeit': 'Empfindlichkeit',
    'einst.farben': 'Farben je Zustand (Hex, mit Komma getrennt)',
    'einst.standardfarben': 'Standardfarben',
    'einst.system': 'System und Updates',
    'einst.autostart': 'Mit Windows starten',
    'einst.update_pruefen': 'Beim Start nach Updates sehen',
    'einst.update_auto': 'Updates ohne Rückfrage einspielen',
    'einst.update_kanal': 'Update-Kanal',
    'einst.kanal_stabil': 'stabil',
    'einst.kanal_test': 'test (auch Vorabversionen)',
    'einst.speichern': 'Speichern',
    'einst.fertig': 'Los geht\'s',
    'einst.gespeichert': 'Gespeichert.',
    'einst.fehlt_name': 'Bitte einen Vornamen eintragen.',
    'einst.fehlt_schluessel': 'Bitte einen API-Schlüssel eintragen.',
    'einst.version': 'Version',
    'konten.titel': 'Verbindungen',
    'konten.hinweis': 'Konten, die Julia für dich nutzen darf. Anmelden tust du selbst im Browser – Julia sieht nie ein Passwort.',
    'konten.google_text': 'Gmail, Kalender und Kontakte. Einmalig nötig: ein eigener OAuth-Client aus der Google Cloud Console.',
    'konten.anleitung': 'Anleitung öffnen',
    'konten.client_id': 'Client-ID',
    'konten.client_secret': 'Client-Secret',
    'konten.verbinden': 'Mit Google verbinden',
    'konten.trennen': 'Trennen',
    'konten.verbunden_als': 'Verbunden als {email}',
    'konten.nicht_verbunden': 'Nicht verbunden',
    'konten.warte_browser': 'Der Browser ist offen – melde dich dort an und erlaube den Zugriff …',
    'konten.secret_gespeichert': 'Secret ist gespeichert. Leer lassen, um es zu behalten.',
    'ecke.unten-rechts': 'unten rechts',
    'ecke.unten-links': 'unten links',
    'ecke.oben-rechts': 'oben rechts',
    'ecke.oben-links': 'oben links',
    'monitor.0': 'Hauptmonitor',
    'monitor.n': 'Monitor {n}',
    'zustand.idle': 'wartet',
    'zustand.listening': 'hört zu',
    'zustand.thinking': 'denkt',
    'zustand.speaking': 'spricht',

    'update.titel': 'Julia-Update',
    'update.aktuell': 'Julia ist aktuell (Version {version}).',
    'update.neu': 'Version {neu} ist verfügbar (du hast {alt}).',
    'update.frage': 'Jetzt einspielen? Julia startet dabei neu.',
    'update.einspielen': 'Einspielen',
    'update.spaeter': 'Später',
    'update.wartet': 'Das Update wird eingespielt, sobald die laufende Aufgabe fertig ist.',
    'update.fehler': 'Update-Prüfung fehlgeschlagen: {fehler}',
    'update.erfolg': 'Julia wurde auf {version} aktualisiert.',
    'update.zurueck': 'Das Update auf {version} ist fehlgeschlagen, Julia läuft wieder auf dem vorherigen Stand. {fehler}',
    'update.verfuegbar_hinweis': 'Update auf {version} verfügbar. Tray-Menü → Nach Updates suchen.',

    'hotkey.fehler': 'Der Hotkey {hotkey} ist schon belegt. In den Einstellungen einen anderen wählen.',
  },

  en: {
    'tray.tooltip': 'Julia',
    'tray.chat': 'Open chat',
    'tray.sprechen': 'Talk',
    'tray.blase': 'Show orb',
    'tray.einstellungen': 'Settings …',
    'tray.neu': 'New conversation',
    'tray.updates': 'Check for updates',
    'tray.protokoll': 'Open log',
    'tray.beenden': 'Quit',

    'chat.titel': 'Julia',
    'chat.platzhalter': 'Write to Julia …',
    'chat.senden': 'Send',
    'chat.stopp': 'Stop',
    'chat.mikro': 'Talk',
    'chat.neu': 'New conversation',
    'chat.einstellungen': 'Settings',
    'chat.leer': 'Julia is waiting. Type something or press {hotkey} to talk.',
    'chat.hoert': 'Julia is listening …',
    'chat.denkt': 'Julia is working …',
    'chat.freigabe': 'Approval needed',
    'chat.auftrag': 'Approve task (hands-on)',
    'chat.auftrag_kategorien': 'Covers',
    'chat.ja': 'Yes, do it',
    'chat.nein': 'No',
    'chat.freigegeben': 'Approved',
    'chat.abgelehnt': 'Declined',
    'chat.kein_schluessel': 'No API key yet. Open the settings and enter it.',
    'chat.abgebrochen': 'Stopped.',
    'chat.fehler': 'Error',
    'chat.beschaeftigt': 'Julia is still busy with the last task. Press Stop to cancel it.',
    'chat.du': 'You',
    'chat.sprache': 'by voice',
    'hinweis.verweigert': 'I can\'t take that on.',
    'hinweis.max_tokens': 'The answer was cut off at the length limit.',
    'hinweis.zu_viele_runden': 'Stopped after 60 steps. Tell me if I should carry on.',

    'einst.titel': 'Julia – Settings',
    'einst.einrichtung_titel': 'Welcome. Quick one-time setup.',
    'einst.einrichtung_text': 'Julia needs your first name, an Anthropic API key and the folders where she may create and change files without asking. Everything can be changed later.',
    'einst.allgemein': 'General',
    'einst.sprachcode': 'Language',
    'einst.name': 'Your first name',
    'einst.schluessel': 'Anthropic API key',
    'einst.schluessel_hinweis': 'Stored encrypted by Windows and never shown again.',
    'einst.schluessel_gesetzt': 'A key is stored. Leave empty to keep it.',
    'einst.modell': 'Model',
    'einst.aufwand': 'Thinking effort',
    'einst.ordner': 'Working directories',
    'einst.ordner_hinweis': 'Julia may write here without asking (GREEN). Everywhere else she asks first.',
    'einst.ordner_hinzu': 'Add folder …',
    'einst.entfernen': 'Remove',
    'einst.sprache': 'Voice and hotkeys',
    'einst.hotkey_sprechen': 'Talk hotkey',
    'einst.hotkey_chat': 'Chat hotkey',
    'einst.vorlesen': 'Read answers aloud',
    'einst.vorlesen_bei': 'when I spoke',
    'einst.vorlesen_immer': 'always',
    'einst.vorlesen_nie': 'never',
    'einst.stimme': 'Voice',
    'einst.sprechtempo': 'Speech rate',
    'einst.blase': 'Orb',
    'einst.blase_an': 'Show orb',
    'einst.monitor': 'Monitor',
    'einst.groesse': 'Size (px)',
    'einst.ecke': 'Corner',
    'einst.deckkraft': 'Opacity',
    'einst.tempo': 'Speed',
    'einst.empfindlichkeit': 'Sensitivity',
    'einst.farben': 'Colours per state (hex, comma separated)',
    'einst.standardfarben': 'Default colours',
    'einst.system': 'System and updates',
    'einst.autostart': 'Start with Windows',
    'einst.update_pruefen': 'Check for updates on start',
    'einst.update_auto': 'Install updates without asking',
    'einst.update_kanal': 'Update channel',
    'einst.kanal_stabil': 'stable',
    'einst.kanal_test': 'test (includes pre-releases)',
    'einst.speichern': 'Save',
    'einst.fertig': 'Let\'s go',
    'einst.gespeichert': 'Saved.',
    'einst.fehlt_name': 'Please enter a first name.',
    'einst.fehlt_schluessel': 'Please enter an API key.',
    'einst.version': 'Version',
    'konten.titel': 'Connections',
    'konten.hinweis': 'Accounts Julia may use for you. You sign in yourself in the browser – Julia never sees a password.',
    'konten.google_text': 'Gmail, Calendar and Contacts. Needed once: your own OAuth client from the Google Cloud Console.',
    'konten.anleitung': 'Open guide',
    'konten.client_id': 'Client ID',
    'konten.client_secret': 'Client secret',
    'konten.verbinden': 'Connect Google',
    'konten.trennen': 'Disconnect',
    'konten.verbunden_als': 'Connected as {email}',
    'konten.nicht_verbunden': 'Not connected',
    'konten.warte_browser': 'The browser is open – sign in there and allow access …',
    'konten.secret_gespeichert': 'Secret is stored. Leave empty to keep it.',
    'ecke.unten-rechts': 'bottom right',
    'ecke.unten-links': 'bottom left',
    'ecke.oben-rechts': 'top right',
    'ecke.oben-links': 'top left',
    'monitor.0': 'Primary monitor',
    'monitor.n': 'Monitor {n}',
    'zustand.idle': 'idle',
    'zustand.listening': 'listening',
    'zustand.thinking': 'thinking',
    'zustand.speaking': 'speaking',

    'update.titel': 'Julia update',
    'update.aktuell': 'Julia is up to date (version {version}).',
    'update.neu': 'Version {neu} is available (you have {alt}).',
    'update.frage': 'Install now? Julia will restart.',
    'update.einspielen': 'Install',
    'update.spaeter': 'Later',
    'update.wartet': 'The update will be installed as soon as the current task is finished.',
    'update.fehler': 'Update check failed: {fehler}',
    'update.erfolg': 'Julia was updated to {version}.',
    'update.zurueck': 'The update to {version} failed; Julia is back on the previous version. {fehler}',
    'update.verfuegbar_hinweis': 'Update to {version} available. Tray menu → Check for updates.',

    'hotkey.fehler': 'The hotkey {hotkey} is already taken. Pick another one in the settings.',
  },
};

function t(sprachcode, schluessel, werte) {
  const tabelle = TEXTE[sprachcode] || TEXTE.de;
  let s = tabelle[schluessel] ?? TEXTE.de[schluessel] ?? schluessel;
  if (werte) for (const [k, v] of Object.entries(werte)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

module.exports = { TEXTE, t };
